---                             # required line for YAML file
 date: "October 2019"           #
 groups :                       # required start list of reduction blocks
  - name : "ARCTIC"             # name of first block
    skip : True
    inst : "ARCTIC"             # instrument, used to identify reduction configuration
    rawdir : "UT191028/ARCTIC"  # directory with raw input images, relative to run directory
    reddir : "red/UT191028/ARCTIC"  # directory for reduced output images, relative to run directory
    biases :                   # optional specification(s) for superbias frame
      - id : "bias"            # identification name and name for output file
        frames : [1,2,3,4,5,6,7,8,9,10]  # list of frame IDs (number or character) to construct superbias if it doesn't exist
    darks :                    # optional specification(s) for superbias frame
      - id : "dark_1200"       # identification name and name for output file
        frames : [82,83,84,85,86,87,88,89,90] # list of frame IDs (number or character) to construct superbias if it doesn't exist
        bias : "bias"          # bias frame used to reduce individual darks before superdark construction
    flats :                    # optional specification(s) for superflat frame
      - id : "domeflat_z"      # identification name and name for first flat
        frames : [1,2,3,4,5]   # list of frame IDs
        bias : "bias"          # bias frame used to reduce individual flats before superflat construction
      - id : "domeflat_r"      # identification name and name for second flat
        frames : [6,7,8,9,10]  # list of frame IDs
        bias : "bias"          # bias frame used to reduce individual flats before superflat construction
      ....
    arcs :                     # frames to be used for wavelength calibration
      - id : "pre"             # ID for first wavecal set
        frames : [19,20,21,22] # frames to use
        bias : "bias"          # bias to use
        wref : "ARCES_wave"    # reference file for template wavecals (pkl file)
        wavecal_type : "echelle"  # type:  echelle or longslit
      - id : "post"            # ID for second wavecal set
        frames : [32]
        bias : "bias"
        wref : "ARCES_wave"
        wavecal_type : "echelle"
